version: '3'

services:
  nginx:
    image: nginx:1.17.2
    container_name: 'nginx-container-prod'
    working_dir: /app
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./frontend_src/dist/frontend:/app/frontend
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/nginx/letsencrypt
    networks:
      - frontend_net
      - backend_net
    links:
      - app

  app:
    build:
      context: .
      dockerfile: app.docker
    container_name: 'app-container-prod'
    working_dir: /app
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./backend_src:/app
      - ./upload:/app/upload
      - ./thumbs:/app/thumbs
    command: 'pm2-runtime dist/main.js'
    env_file:
      - ./.env.prod
    networks:
      - backend_net
    links:
      - mongo-service
      - mailer-service

  mongo-service:
    image: mongo:4.0.10-xenial
    container_name: 'mongo-container-prod'
    ports:
      - '30001:27017'
    restart: always
    volumes:
      - ql_practice_db_prod:/data/db
    env_file:
      - ./.env.prod
    command: mongod --replSet rs_qlp
    networks:
      - backend_net

  mailer-service:
    image: catatnight/postfix
    container_name: 'mailer-service-prod'
    ports:
      - '587:587'
    volumes:
      - ./config/mailer/opendkim:/etc/opendkim
      - /etc/letsencrypt/live/ql-practice.ru/fullchain.pem:/etc/postfix/certs/public.crt
      - /etc/letsencrypt/live/ql-practice.ru/privkey.pem:/etc/postfix/certs/private.key
    env_file:
      - ./.env.mailer
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    networks:
      - backend_net

networks:
  frontend_net:
    internal: false
  backend_net:
    internal: true

volumes:
  ql_practice_db_prod:
    driver: local
    driver_opts:
      type: bind
      device: /root/project/database
