version: '3'

services:
  app:
    image: ql/build-app
    container_name: 'app-container-build'
    working_dir: /app
    volumes:
      - ../backend_src:/app
      - ../upload:/app/upload
      - ../thumbs:/app/thumbs
    links:
      - mongodb-service
    command: 'npm run start'
    env_file:
      - ./.env.build
    networks:
      - backend_net

  mongodb-service:
    image: mongo:4.0.10-xenial
    container_name: 'mongo-container-prod'
    ports:
      - '30001:27017'
    restart: always
    volumes:
      - ../../database:/data/db
    command: mongod --replSet rs_qlp
    env_file:
      - ./.env.build
    networks:
      - backend_net

networks:
  backend_net:
    internal: true
