version: '3'

services:
  nginx:
    image: nginx:1.17.2
    container_name: 'nginx-container-prod'
    working_dir: /app
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../frontend_src/dist/frontend:/app/frontend
      - ../config/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/nginx/letsencrypt
    networks:
      - frontend_net
      - backend_net
    links:
      - app

  app:
    image: ql/app
    container_name: 'app-container-prod'
    working_dir: /app
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ../upload:/app/upload
      - ../thumbs:/app/thumbs
      - ../config/pm2.json:/app/pm2.json
      - /etc/letsencrypt:/etc/letsencrypt
      - ../config/mailer/opendkim/keys/mail.ql-practice.ru:/app/opendkim
    command: 'pm2-runtime start pm2.json'
    networks:
      - frontend_net
      - backend_net
    links:
      - mongodb-service
      - mailer-service

  mongodb-service:
    image: mongo:4.0.10-xenial
    container_name: 'mongo-container-prod'
    ports:
      - '30001:27017'
    restart: always
    volumes:
      - ../../database:/data/db
    env_file:
      MONGO_INITDB_DATABASE: 'qlp_practice'
    command: mongod --replSet rs_qlp
    networks:
      - backend_net

  mailer-service:
    image: catatnight/postfix
    hostname: 'mail'
    domainname: 'ql-practice.ru'
    container_name: 'mailer-service-prod'
    ports:
      - '25:25'
    volumes:
      - ../config/mailer/opendkim:/etc/opendkim
      - /etc/letsencrypt/live/ql-practice.ru/fullchain.pem:/etc/postfix/certs/public.crt
      - /etc/letsencrypt/live/ql-practice.ru/privkey.pem:/etc/postfix/certs/private.key
    env_file:
      - ./.env.mailer
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    networks:
      - frontend_net
      - backend_net

networks:
  frontend_net:
    internal: false
  backend_net:
    internal: true